set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/new_reg[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/new_reg[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[11]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/TransactRegiMap_0/load_DAC2]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/TransactRegiMap_0/wen]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[13]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/spi_interface_ctrl_0/SCK]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[4]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/TransactRegiMap_0/ack]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[9]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/spi_interface_ctrl_0/bLDAC]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/bCS[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[10]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/TransactRegiMap_0/req]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[14]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/spi_interface_ctrl_0/SDI]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[15]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/TransactRegiMap_0/load_DAC1]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/bCS[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/state[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/state[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/state[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/state_0[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/state_0[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/state_0[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/SPI_INST[0].spi_instance/state[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/SPI_INST[0].spi_instance/state[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/spi_interface_ctrl_0/inst/SPI_INST[0].spi_instance/state[2]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list qpixlar_bd_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {qpixlar_bd_i/spi_interface_ctrl_0/inst/state_0[0]} {qpixlar_bd_i/spi_interface_ctrl_0/inst/state_0[1]} {qpixlar_bd_i/spi_interface_ctrl_0/inst/state_0[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {qpixlar_bd_i/spi_interface_ctrl_0/inst/SPI_INST[0].spi_instance/state[0]} {qpixlar_bd_i/spi_interface_ctrl_0/inst/SPI_INST[0].spi_instance/state[1]} {qpixlar_bd_i/spi_interface_ctrl_0/inst/SPI_INST[0].spi_instance/state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {qpixlar_bd_i/spi_interface_ctrl_0/inst/state[0]} {qpixlar_bd_i/spi_interface_ctrl_0/inst/state[1]} {qpixlar_bd_i/spi_interface_ctrl_0/inst/state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {qpixlar_bd_i/spi_interface_ctrl_0/bCS[0]} {qpixlar_bd_i/spi_interface_ctrl_0/bCS[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {qpixlar_bd_i/spi_interface_ctrl_0/new_reg[0]} {qpixlar_bd_i/spi_interface_ctrl_0/new_reg[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/QpixMask[0]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[1]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[2]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[3]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[4]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[5]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[6]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[7]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[8]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[9]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[10]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[11]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[12]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[13]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[14]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[0]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[1]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[2]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[3]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[4]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[5]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[6]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[7]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[8]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[9]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[10]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[11]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[12]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[13]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[14]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/SHDN[0]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[1]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[2]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[3]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[4]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[5]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[6]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[7]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[8]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[9]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[10]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[11]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[12]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[13]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[14]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[0]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[1]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[2]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[3]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[4]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[5]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[6]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[7]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[8]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[9]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[10]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[11]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[12]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[13]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[14]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list qpixlar_bd_i/TransactRegiMap_0/ack]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list qpixlar_bd_i/spi_interface_ctrl_0/bLDAC]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list qpixlar_bd_i/TransactRegiMap_0/load_DAC1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list qpixlar_bd_i/TransactRegiMap_0/load_DAC2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list qpixlar_bd_i/TransactRegiMap_0/req]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list qpixlar_bd_i/spi_interface_ctrl_0/SCK]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list qpixlar_bd_i/spi_interface_ctrl_0/SDI]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list qpixlar_bd_i/TransactRegiMap_0/wen]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK1]
