set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/sample_valid]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_loadData]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_control]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_cal_control]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_RST_EXT]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_cal_control]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_control]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_DataIn]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_deltaT]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_loadData]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_RST_EXT]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_CLKin2]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_CLKin]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_DataIn]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_deltaT]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_CLKin]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_CLKin2]

set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_selDefData]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_serialOutCnt]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_startup]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_Ext_POR]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_selDefData]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_serialOutCnt]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_startup]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/FPGA_ID[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/FPGA_ID[1]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list qpixlar_bd_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/FPGA_ID[0]} {qpixlar_bd_i/TransactRegiMap_0/FPGA_ID[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_cal_control]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_CLKin]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_CLKin2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_control]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_DataIn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_deltaT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_loadData]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_RST_EXT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_selDefData]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_serialOutCnt]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_startup]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_cal_control]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_CLKin]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_CLKin2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_control]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_DataIn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_deltaT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_Ext_POR]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_loadData]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_RST_EXT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_selDefData]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_serialOutCnt]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_startup]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/sample_valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK1]
