set_property MARK_DEBUG true [get_nets qpixlar_bd_i/axis_data_fifo_0/m_axis_tlast]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/axis_data_fifo_0/m_axis_tready]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/axis_data_fifo_0/m_axis_tvalid]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/axis_data_fifo_0/s_axis_aresetn]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/axis_data_fifo_0/s_axis_tlast]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/axis_data_fifo_0/s_axis_tready]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/axis_data_fifo_0/s_axis_tvalid]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[20]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[23]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/FPGA_ID[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[21]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[22]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[16]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[17]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[24]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[26]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[30]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[19]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[31]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[18]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[27]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[28]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[29]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/FPGA_ID[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[25]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/PacketLength[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/QpixMask[12]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/TransactRegiMap_0/force_valid]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/TransactRegiMap_0/load_DAC1]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/TransactRegiMap_0/load_DAC2]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/SHDN[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[17]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[26]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[23]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_1[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[17]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[29]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[31]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[30]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[22]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[29]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[17]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[24]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_1[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[31]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[28]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[30]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[22]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[18]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[25]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[28]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[24]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[18]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[19]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[25]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[28]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[22]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[29]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_3[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[20]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[20]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[26]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[23]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_1[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[16]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[17]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[23]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[22]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_3[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_3[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[19]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[25]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[31]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_3[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[20]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_1[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[19]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[25]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[27]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[26]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_1[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[17]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[13]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_3[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[16]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_1[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[14]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[31]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[18]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[30]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[16]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[28]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[27]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[10]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_a[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[20]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[15]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[3]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[24]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[26]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[7]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[30]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[19]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[25]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_1[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_3[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[21]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[21]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[21]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[12]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[16]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_3[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[24]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[1]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_0[8]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[18]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[29]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[27]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[9]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[27]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[11]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_3[0]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[21]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[16]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_1[2]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_2[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_4[31]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[4]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_8[23]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[6]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_7[24]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[5]}]
set_property MARK_DEBUG true [get_nets {qpixlar_bd_i/TransactRegiMap_0/reg_9[9]}]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_deltaT]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_loadData]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_RST_EXT]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_cal_control]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_loadData]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_cal_control]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_control]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad2_DataIn]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_control]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_DataIn]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_RST_EXT]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/sample_valid]
set_property MARK_DEBUG true [get_nets qpixlar_bd_i/qpix_reg_rtl_0/opad_deltaT]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list qpixlar_bd_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_1[0]} {qpixlar_bd_i/TransactRegiMap_0/reg_1[1]} {qpixlar_bd_i/TransactRegiMap_0/reg_1[2]} {qpixlar_bd_i/TransactRegiMap_0/reg_1[4]} {qpixlar_bd_i/TransactRegiMap_0/reg_1[5]} {qpixlar_bd_i/TransactRegiMap_0/reg_1[6]} {qpixlar_bd_i/TransactRegiMap_0/reg_1[8]} {qpixlar_bd_i/TransactRegiMap_0/reg_1[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 20 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_0[0]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[1]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[2]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[3]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[4]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[5]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[6]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[7]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[8]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[9]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[10]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[11]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[12]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[13]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[14]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[15]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[16]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[17]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[24]} {qpixlar_bd_i/TransactRegiMap_0/reg_0[25]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_a[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_3[0]} {qpixlar_bd_i/TransactRegiMap_0/reg_3[1]} {qpixlar_bd_i/TransactRegiMap_0/reg_3[2]} {qpixlar_bd_i/TransactRegiMap_0/reg_3[4]} {qpixlar_bd_i/TransactRegiMap_0/reg_3[5]} {qpixlar_bd_i/TransactRegiMap_0/reg_3[6]} {qpixlar_bd_i/TransactRegiMap_0/reg_3[8]} {qpixlar_bd_i/TransactRegiMap_0/reg_3[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[0]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[1]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[2]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[3]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[4]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[5]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[6]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[7]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[8]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[9]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[10]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[11]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[12]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[13]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[14]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg2[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 17 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_9[0]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[1]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[2]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[3]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[4]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[5]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[6]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[7]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[8]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[9]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[10]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[11]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[12]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[13]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[14]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[15]} {qpixlar_bd_i/TransactRegiMap_0/reg_9[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/QpixMask[0]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[1]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[2]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[3]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[4]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[5]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[6]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[7]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[8]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[9]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[10]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[11]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[12]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[13]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[14]} {qpixlar_bd_i/TransactRegiMap_0/QpixMask[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_7[0]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[1]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[2]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[3]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[4]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[5]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[6]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[7]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[8]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[9]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[10]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[11]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[12]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[13]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[14]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[15]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[16]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[17]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[18]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[19]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[20]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[21]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[22]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[23]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[24]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[25]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[26]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[27]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[28]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[29]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[30]} {qpixlar_bd_i/TransactRegiMap_0/reg_7[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_4[0]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[1]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[2]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[3]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[4]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[5]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[6]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[7]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[8]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[9]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[10]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[11]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[12]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[13]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[14]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[15]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[16]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[17]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[18]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[19]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[20]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[21]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[22]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[23]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[24]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[25]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[26]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[27]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[28]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[29]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[30]} {qpixlar_bd_i/TransactRegiMap_0/reg_4[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_2[0]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[1]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[2]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[3]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[4]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[5]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[6]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[7]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[8]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[9]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[10]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[11]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[12]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[13]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[14]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[15]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[16]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[17]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[18]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[19]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[20]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[21]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[22]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[23]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[24]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[25]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[26]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[27]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[28]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[29]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[30]} {qpixlar_bd_i/TransactRegiMap_0/reg_2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/SHDN[0]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[1]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[2]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[3]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[4]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[5]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[6]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[7]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[8]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[9]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[10]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[11]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[12]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[13]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[14]} {qpixlar_bd_i/TransactRegiMap_0/SHDN[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[0]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[1]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[2]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[3]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[4]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[5]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[6]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[7]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[8]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[9]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[10]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[11]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[12]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[13]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[14]} {qpixlar_bd_i/TransactRegiMap_0/DAC_reg1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 2 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/FPGA_ID[0]} {qpixlar_bd_i/TransactRegiMap_0/FPGA_ID[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/PacketLength[0]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[1]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[2]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[3]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[4]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[5]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[6]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[7]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[8]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[9]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[10]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[11]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[12]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[13]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[14]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[15]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[16]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[17]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[18]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[19]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[20]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[21]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[22]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[23]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[24]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[25]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[26]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[27]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[28]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[29]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[30]} {qpixlar_bd_i/TransactRegiMap_0/PacketLength[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {qpixlar_bd_i/TransactRegiMap_0/reg_8[0]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[1]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[2]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[3]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[4]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[5]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[6]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[7]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[8]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[9]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[10]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[11]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[12]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[13]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[14]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[15]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[16]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[17]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[18]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[19]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[20]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[21]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[22]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[23]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[24]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[25]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[26]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[27]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[28]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[29]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[30]} {qpixlar_bd_i/TransactRegiMap_0/reg_8[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list qpixlar_bd_i/TransactRegiMap_0/force_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list qpixlar_bd_i/TransactRegiMap_0/load_DAC1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list qpixlar_bd_i/TransactRegiMap_0/load_DAC2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list qpixlar_bd_i/axis_data_fifo_0/m_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list qpixlar_bd_i/axis_data_fifo_0/m_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list qpixlar_bd_i/axis_data_fifo_0/m_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_cal_control]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_control]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_DataIn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_deltaT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_loadData]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad2_RST_EXT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_cal_control]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_control]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_DataIn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_deltaT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_loadData]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/opad_RST_EXT]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list qpixlar_bd_i/axis_data_fifo_0/s_axis_aresetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list qpixlar_bd_i/axis_data_fifo_0/s_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list qpixlar_bd_i/axis_data_fifo_0/s_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list qpixlar_bd_i/axis_data_fifo_0/s_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list qpixlar_bd_i/qpix_reg_rtl_0/sample_valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK1]
